// Mock data for AntiquaChain MVP

import type { Listing, Category, User, MarketInsight } from '@/types'

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Paintings', slug: 'paintings', icon: '🖼️', count: 342 },
  { id: '2', name: 'Sculptures', slug: 'sculptures', icon: '🗿', count: 187 },
  { id: '3', name: 'Coins', slug: 'coins', icon: '🪙', count: 891 },
  { id: '4', name: 'Vintage Jewelry', slug: 'jewelry', icon: '💎', count: 563 },
  { id: '5', name: 'Rare Books', slug: 'books', icon: '📜', count: 234 },
  { id: '6', name: 'Artifacts', slug: 'artifacts', icon: '🏺', count: 412 },
  { id: '7', name: 'Ancient Weapons', slug: 'weapons', icon: '⚔️', count: 156 },
  { id: '8', name: 'Vintage Furniture', slug: 'furniture', icon: '🪑', count: 298 },
  { id: '9', name: 'Clocks', slug: 'clocks', icon: '🕰️', count: 143 },
  { id: '10', name: 'Manuscripts', slug: 'manuscripts', icon: '📿', count: 89 },
  { id: '11', name: 'Collectibles', slug: 'collectibles', icon: '🎭', count: 724 },
  { id: '12', name: 'Cultural Relics', slug: 'relics', icon: '🏛️', count: 201 },
]

export const MOCK_SELLERS: User[] = [
  {
    id: 'u1', name: 'Alessandro Ferretti', email: 'a.ferretti@example.com',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    walletAddress: '0x742d35Cc6634C0532925a3b8D4C9C56e7d5e3F2',
    role: 'seller', rating: 4.9, reviewCount: 312, joinedAt: '2021-03-14', verified: true,
  },
  {
    id: 'u2', name: 'Sophia Hartmann', email: 's.hartmann@example.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop',
    walletAddress: '0x1a2B3c4D5e6F7a8B9c0D1e2F3a4B5c6D7e8F9a0B',
    role: 'seller', rating: 4.8, reviewCount: 187, joinedAt: '2020-07-22', verified: true,
  },
  {
    id: 'u3', name: 'Rajiv Mehta', email: 'r.mehta@example.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop',
    walletAddress: '0xDeAdBeEf1234567890AbCdEf1234567890AbCdEf',
    role: 'seller', rating: 4.7, reviewCount: 94, joinedAt: '2022-01-10', verified: true,
  },
]

const now = new Date()
const inHours = (h: number) => new Date(now.getTime() + h * 3600000).toISOString()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'Ming Dynasty Blue & White Porcelain Vase',
    description: 'An exceptional Ming Dynasty (1368–1644) blue-and-white porcelain vase of the Wanli period. Hand-painted with mythological dragons chasing flaming pearls amid cloud scrolls. Provenance documented back to 1899 at Sotheby\'s London auction. Complete with certificate of authenticity from the Smithsonian Institution.',
    category: CATEGORIES[5],
    era: '14th–17th Century',
    condition: 'excellent',
    type: 'auction',
    price: 2.4,
    currency: 'ETH',
    priceUsd: 8400,
    images: [
      { id: 'i1', url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop', alt: 'Ming Vase Front', isPrimary: true },
      { id: 'i2', url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&h=600&fit=crop', alt: 'Ming Vase Detail', isPrimary: false },
    ],
    seller: MOCK_SELLERS[0],
    sellerRating: 4.9,
    isVerified: true,
    authenticityScore: 97,
    provenance: [
      { id: 'p1', txHash: '0xabc123...', from: '0x0000...0000', to: '0x742d...3F2', timestamp: daysAgo(365), event: 'minted', note: 'Initial NFT registration' },
      { id: 'p2', txHash: '0xdef456...', from: '0x742d...3F2', to: '0x1a2B...0B', timestamp: daysAgo(180), event: 'verified', note: 'Authenticated by Smithsonian AI Lab' },
      { id: 'p3', txHash: '0x789xyz...', from: '0x1a2B...0B', to: '0x742d...3F2', timestamp: daysAgo(90), event: 'transferred', note: 'Ownership transfer to current seller' },
    ],
    artifactId: 'AQ-2024-0001',
    auctionEndsAt: inHours(11),
    currentBid: 2.4,
    bidCount: 23,
    location: 'Milan, Italy',
    shipping: ['Insured Worldwide', 'Climate Controlled', 'Museum Crating'],
    tags: ['Ming', 'China', 'Porcelain', 'Dragon', 'Rare'],
    views: 4821,
    watchlistCount: 342,
    createdAt: daysAgo(30),
  },
  {
    id: '2',
    title: 'Roman Gold Aureus — Emperor Augustus (27 BC)',
    description: 'An extremely rare gold aureus struck during the reign of Emperor Augustus. Obverse features a laureate portrait with "AUGUSTUS" inscription. Among fewer than 14 known surviving examples from this mint. Acquired from the Harlan J. Berk collection. Graded MS62 by NGC.',
    category: CATEGORIES[2],
    era: '27 BC – 14 AD',
    condition: 'mint',
    type: 'fixed',
    price: 5.8,
    currency: 'ETH',
    priceUsd: 20300,
    images: [
      { id: 'i3', url: 'https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?w=800&h=600&fit=crop', alt: 'Roman Coin Obverse', isPrimary: true },
      { id: 'i4', url: 'https://images.unsplash.com/photo-1596522354195-e84ae3c98731?w=800&h=600&fit=crop', alt: 'Roman Coin Reverse', isPrimary: false },
    ],
    seller: MOCK_SELLERS[1],
    sellerRating: 4.8,
    isVerified: true,
    authenticityScore: 99,
    provenance: [
      { id: 'p4', txHash: '0x111aaa...', from: '0x0000...0000', to: '0x1a2B...0B', timestamp: daysAgo(720), event: 'minted', note: 'Registration from Harlan Berk Estate' },
      { id: 'p5', txHash: '0x222bbb...', from: '0x1a2B...0B', to: '0x1a2B...0B', timestamp: daysAgo(60), event: 'verified', note: 'NGC Grading MS62' },
    ],
    artifactId: 'AQ-2024-0002',
    location: 'Vienna, Austria',
    shipping: ['Insured Worldwide', 'Vault Delivery Available'],
    tags: ['Roman', 'Augustus', 'Gold', 'Coin', 'Ancient'],
    views: 7244,
    watchlistCount: 589,
    createdAt: daysAgo(45),
  },
  {
    id: '3',
    title: '18th Century French Ormolu Mantel Clock',
    description: 'A magnificent Louis XVI ormolu-mounted porcelain mantel clock. Signed by Parisian clockmaker Lepaute. The case surmounted by a bronze figure of Chronos. Original movement with all original parts. Exhibited at the Louvre in 1987.',
    category: CATEGORIES[8],
    era: '18th Century',
    condition: 'excellent',
    type: 'auction',
    price: 1.2,
    currency: 'ETH',
    priceUsd: 4200,
    images: [
      { id: 'i5', url: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=800&h=600&fit=crop', alt: 'Mantel Clock', isPrimary: true },
    ],
    seller: MOCK_SELLERS[2],
    sellerRating: 4.7,
    isVerified: true,
    authenticityScore: 94,
    provenance: [
      { id: 'p6', txHash: '0x333ccc...', from: '0x0000...0000', to: '0xDeAd...dEf', timestamp: daysAgo(200), event: 'minted', note: 'IPFS doc: QmXyz...' },
    ],
    artifactId: 'AQ-2024-0003',
    auctionEndsAt: inHours(38),
    currentBid: 1.2,
    bidCount: 11,
    location: 'Paris, France',
    shipping: ['Insured Europe', 'Professional Packing'],
    tags: ['Louis XVI', 'Clock', 'Bronze', 'French', 'Ormolu'],
    views: 2910,
    watchlistCount: 198,
    createdAt: daysAgo(15),
  },
  {
    id: '4',
    title: 'Ancient Egyptian Ushabti Figurine — 19th Dynasty',
    description: 'Authentic faience ushabti from the 19th Dynasty (1295–1186 BC). Turquoise-blue glazed with black hieroglyphic inscriptions naming the owner Ramose. From an important European Private Collection. Accompanied by thermoluminescence dating certificate.',
    category: CATEGORIES[11],
    era: '1295–1186 BC',
    condition: 'good',
    type: 'fixed',
    price: 0.85,
    currency: 'ETH',
    priceUsd: 2975,
    images: [
      { id: 'i6', url: 'https://images.unsplash.com/photo-1568952433726-3896e3881c65?w=800&h=600&fit=crop', alt: 'Egyptian Ushabti', isPrimary: true },
    ],
    seller: MOCK_SELLERS[0],
    sellerRating: 4.9,
    isVerified: true,
    authenticityScore: 92,
    provenance: [
      { id: 'p7', txHash: '0x444ddd...', from: '0x0000...0000', to: '0x742d...3F2', timestamp: daysAgo(120), event: 'minted', note: 'Imported from Swiss collection 2019' },
    ],
    artifactId: 'AQ-2024-0004',
    location: 'Geneva, Switzerland',
    shipping: ['Insured Worldwide', 'Export Licensed'],
    tags: ['Egyptian', 'Ushabti', 'Dynasty', 'Faience', 'Ancient'],
    views: 3540,
    watchlistCount: 267,
    createdAt: daysAgo(22),
  },
  {
    id: '5',
    title: 'Samurai Katana — Edo Period (c. 1680)',
    description: 'A superb Edo period katana signed by Bizen Osafune school smith Sukesada. The blade in excellent polish with wide tempering pattern (hamon). Housed in original lacquered koshirae. Accompanied by NBTHK Tokubetsu Hozon certificate (Special Preservation Grade).',
    category: CATEGORIES[6],
    era: '17th Century',
    condition: 'excellent',
    type: 'auction',
    price: 3.1,
    currency: 'ETH',
    priceUsd: 10850,
    images: [
      { id: 'i7', url: 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=800&h=600&fit=crop', alt: 'Samurai Katana', isPrimary: true },
    ],
    seller: MOCK_SELLERS[1],
    sellerRating: 4.8,
    isVerified: true,
    authenticityScore: 96,
    provenance: [
      { id: 'p8', txHash: '0x555eee...', from: '0x0000...0000', to: '0x1a2B...0B', timestamp: daysAgo(300), event: 'minted', note: 'NBTHK Tokubetsu Hozon certified' },
    ],
    artifactId: 'AQ-2024-0005',
    auctionEndsAt: inHours(62),
    currentBid: 3.1,
    bidCount: 18,
    location: 'Tokyo, Japan',
    shipping: ['Insured Worldwide', 'Export Licensed', 'Museum Crating'],
    tags: ['Samurai', 'Katana', 'Edo', 'Japan', 'Sword'],
    views: 6120,
    watchlistCount: 445,
    createdAt: daysAgo(18),
  },
  {
    id: '6',
    title: 'Art Nouveau Diamond & Enamel Brooch — Lalique',
    description: 'A breathtaking Art Nouveau brooch by René Lalique, circa 1900. Featuring a naturalistic dragonfly motif in plique-à-jour enamel with rose-cut diamonds. One of the finest surviving examples of Lalique\'s jewelry art. Exhibited at the Museum of Arts and Design, NYC.',
    category: CATEGORIES[3],
    era: 'Early 20th Century',
    condition: 'mint',
    type: 'fixed',
    price: 8.2,
    currency: 'ETH',
    priceUsd: 28700,
    images: [
      { id: 'i8', url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&h=600&fit=crop', alt: 'Lalique Brooch', isPrimary: true },
    ],
    seller: MOCK_SELLERS[2],
    sellerRating: 4.7,
    isVerified: true,
    authenticityScore: 98,
    provenance: [
      { id: 'p9', txHash: '0x666fff...', from: '0x0000...0000', to: '0xDeAd...dEf', timestamp: daysAgo(500), event: 'minted', note: 'Christie\'s Paris provenance' },
    ],
    artifactId: 'AQ-2024-0006',
    location: 'New York, USA',
    shipping: ['Insured Worldwide', 'Vault Delivery Available', 'Custom Insurance'],
    tags: ['Lalique', 'Art Nouveau', 'Diamond', 'Enamel', 'Jewelry'],
    views: 9834,
    watchlistCount: 712,
    createdAt: daysAgo(60),
  },
]

export const MARKET_INSIGHTS: MarketInsight[] = [
  { category: 'Ancient Coins', avgPrice: 4200, priceChange: 18.4, volume: 234, trending: true },
  { category: 'Ming Ceramics', avgPrice: 12800, priceChange: 11.2, volume: 89, trending: true },
  { category: 'Japanese Swords', avgPrice: 8900, priceChange: 7.6, volume: 156, trending: false },
  { category: 'Art Nouveau Jewelry', avgPrice: 18400, priceChange: 23.1, volume: 67, trending: true },
  { category: 'Egyptian Artifacts', avgPrice: 3100, priceChange: -2.3, volume: 178, trending: false },
  { category: 'Renaissance Art', avgPrice: 45000, priceChange: 9.8, volume: 34, trending: false },
]

export const PORTFOLIO_DATA = [
  { month: 'Sep', value: 24000 },
  { month: 'Oct', value: 28500 },
  { month: 'Nov', value: 26800 },
  { month: 'Dec', value: 31200 },
  { month: 'Jan', value: 38900 },
  { month: 'Feb', value: 42100 },
  { month: 'Mar', value: 47300 },
]
